spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://162.14.117.124:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 8088

#日志记录配置
logging:
  level:
    root: warn
    cn.dicraft: info
  file:
    name: log/blog-pro.log